package me.ewriter.bangumitv.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANGUMI_CALENDAR".
 */
@Entity
public class BangumiCalendar {

    @Id
    private Long id;

    @NotNull
    private String name_cn;
    private int air_weekday;
    private int bangumi_id;
    private Integer bangumi_total;
    private Float bangumi_average;
    private String large_image;
    private String common_image;

    @Generated
    public BangumiCalendar() {
    }

    public BangumiCalendar(Long id) {
        this.id = id;
    }

    @Generated
    public BangumiCalendar(Long id, String name_cn, int air_weekday, int bangumi_id, Integer bangumi_total, Float bangumi_average, String large_image, String common_image) {
        this.id = id;
        this.name_cn = name_cn;
        this.air_weekday = air_weekday;
        this.bangumi_id = bangumi_id;
        this.bangumi_total = bangumi_total;
        this.bangumi_average = bangumi_average;
        this.large_image = large_image;
        this.common_image = common_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName_cn() {
        return name_cn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_cn(@NotNull String name_cn) {
        this.name_cn = name_cn;
    }

    public int getAir_weekday() {
        return air_weekday;
    }

    public void setAir_weekday(int air_weekday) {
        this.air_weekday = air_weekday;
    }

    public int getBangumi_id() {
        return bangumi_id;
    }

    public void setBangumi_id(int bangumi_id) {
        this.bangumi_id = bangumi_id;
    }

    public Integer getBangumi_total() {
        return bangumi_total;
    }

    public void setBangumi_total(Integer bangumi_total) {
        this.bangumi_total = bangumi_total;
    }

    public Float getBangumi_average() {
        return bangumi_average;
    }

    public void setBangumi_average(Float bangumi_average) {
        this.bangumi_average = bangumi_average;
    }

    public String getLarge_image() {
        return large_image;
    }

    public void setLarge_image(String large_image) {
        this.large_image = large_image;
    }

    public String getCommon_image() {
        return common_image;
    }

    public void setCommon_image(String common_image) {
        this.common_image = common_image;
    }

}
