package me.ewriter.bangumitv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.ewriter.bangumitv.dao.BangumiCalendar;

import me.ewriter.bangumitv.dao.BangumiCalendarDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bangumiCalendarDaoConfig;

    private final BangumiCalendarDao bangumiCalendarDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bangumiCalendarDaoConfig = daoConfigMap.get(BangumiCalendarDao.class).clone();
        bangumiCalendarDaoConfig.initIdentityScope(type);

        bangumiCalendarDao = new BangumiCalendarDao(bangumiCalendarDaoConfig, this);

        registerDao(BangumiCalendar.class, bangumiCalendarDao);
    }
    
    public void clear() {
        bangumiCalendarDaoConfig.getIdentityScope().clear();
    }

    public BangumiCalendarDao getBangumiCalendarDao() {
        return bangumiCalendarDao;
    }

}
