package me.ewriter.bangumitv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.ewriter.bangumitv.dao.BangumiCalendar;
import me.ewriter.bangumitv.dao.MyCollection;

import me.ewriter.bangumitv.dao.BangumiCalendarDao;
import me.ewriter.bangumitv.dao.MyCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bangumiCalendarDaoConfig;
    private final DaoConfig myCollectionDaoConfig;

    private final BangumiCalendarDao bangumiCalendarDao;
    private final MyCollectionDao myCollectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bangumiCalendarDaoConfig = daoConfigMap.get(BangumiCalendarDao.class).clone();
        bangumiCalendarDaoConfig.initIdentityScope(type);

        myCollectionDaoConfig = daoConfigMap.get(MyCollectionDao.class).clone();
        myCollectionDaoConfig.initIdentityScope(type);

        bangumiCalendarDao = new BangumiCalendarDao(bangumiCalendarDaoConfig, this);
        myCollectionDao = new MyCollectionDao(myCollectionDaoConfig, this);

        registerDao(BangumiCalendar.class, bangumiCalendarDao);
        registerDao(MyCollection.class, myCollectionDao);
    }
    
    public void clear() {
        bangumiCalendarDaoConfig.getIdentityScope().clear();
        myCollectionDaoConfig.getIdentityScope().clear();
    }

    public BangumiCalendarDao getBangumiCalendarDao() {
        return bangumiCalendarDao;
    }

    public MyCollectionDao getMyCollectionDao() {
        return myCollectionDao;
    }

}
